Feature/telegram
IgnazioGul/QualityDevelopmentProject pull request #4
Opened 2023-01-10 16:20 UTC by GiancarmeloPittala

Implementazione del sistema per la comunicazione a telegram tramite libreria python-telegram-bot

2023-01-10 18:03 UTC, TendTo requested changes

2023-01-10 18:03 UTC, TendTo commented on src/services/index.py
> +async def get_city_by_query(query):
Manca il typehint nella firma della funzione

2023-01-10 18:03 UTC, TendTo commented on src/services/index.py
> +        locations = []
`location` potrebbe essere inizializzato direttamente ad un array vuoto e l'except potrebbe solo loggare l'eventuale errore (o non fare nulla)

```py
    locations = []
    try:
        locations = WeatherCall.get_coordinates(query, 5)
    except TypeError:
        pass
```

2023-01-10 18:03 UTC, TendTo commented on src/services/index.py
> +                title=f"{ location['name'] if 'name' in location else '' }, { location['state'] if 'state' in location else '' } - { location['country'] if 'state' in location else '' } ",
Invece della struttura utilizzata con l'operatore ternario per prendere i campi opzionali dal dizionario, si può utilizzare la forma più compatta 

```py
InlineQueryResultArticle(
                id=str(uuid4()),
                title=f"{ location.get('name', '') }, { location.get('state', '') } - { location.get('coutry', '') } ",
# ...
```

2023-01-10 18:03 UTC, TendTo commented on src/services/index.py
> +def get_message(meteo: meteo_prop) -> str:
Non sono proprio sicuro questo tipo di type definition per `meteo_prop` sia corretto. Quello che hai fatto è creare un dizionario che contiene dei tipi. Prova a vedere l'utilizzo dei [TypedDict](https://docs.python.org/3/library/typing.html#typing.TypedDict).

2023-01-10 18:05 UTC, TendTo commented
Inoltre aggiorna i requirements.txt aggiungendo le librerie utilizzate (in particolare quella per telegram di python).
Puoi farlo in maniera brutale con il comando `pip3 freeze > requirements.txt`, ma sovrascriverai quello che c'è già. Altrimenti puoi appendere le librerie mancanti con `pip3 freeze >> requirements.txt`

2023-01-13 07:08 UTC, GiancarmeloPittala commented on src/services/index.py
> +async def get_city_by_query(query):
Done

2023-01-13 07:11 UTC, GiancarmeloPittala commented on src/services/index.py
> +        locations = []
Done

2023-01-13 07:13 UTC, GiancarmeloPittala commented on src/services/index.py
> +                title=f"{ location['name'] if 'name' in location else '' }, { location['state'] if 'state' in location else '' } - { location['country'] if 'state' in location else '' } ",
Ottimo, non lo conoscevo questo operatore get per i dictionary molto utile

2023-01-30 14:11 UTC, GiancarmeloPittala commented on src/services/index.py
> +def get_message(meteo: meteo_prop) -> str:
Ho creato un dict MeteoProp usando Dict, List, Union di typing

2023-02-01 19:16 UTC, IgnazioGul approved these changes

2023-02-01 19:16 UTC, merged